# ReProSeg with DeepLab v3 backbone configuration

# Network
backbone_network: deeplab_v3

# Network Parameters
num_prototypes: 0  # Use backbone output channels
bias: false

disable_pretrained: false
train_backbone_during_pretrain: false

# Loss configuration
criterion: weighted_dice

loss_weights:
  alignment: 0.1
  jsd: 0.01
  tanh: 0.1
  classification: 10.0