# @package hydra.job_logging
version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "[%(asctime)s - %(levelname)-7s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    filename: ${hydra:runtime.output_dir}/train.log
    mode: w
root:
  level: INFO
  handlers: [console, file]
