searchSpaceFile: search_space.json
trialCommand: python src/scripts/run.py

experimentName: learning_rates_tuning
trialConcurrency: 1
maxTrialNumber: 20
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
assessor:
  name: Medianstop
  classArgs:
    optimize_mode: maximize
    start_step: 70   
trainingService:
  platform: local
