searchSpaceFile: search_space.json
trialCommand: bash src/scripts/start_nni_trial.sh
trialCodeDirectory: ~/src/ReProSeg

experimentName: learning_rates_tuning
trialConcurrency: 3
maxTrialNumber: 20
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
assessor:
  name: Medianstop
  classArgs:
    optimize_mode: maximize
    start_step: 70   
trainingService:
  platform: local
